apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: digital-replicaset
  namespace: digital  # Specify the namespace here
  labels:
    app: nginx
spec:
  replicas: 3  # Number of desired pod replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
